version: '2'
services:
  acropolis:
    privileged: true
    image: acropolis
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DOINIT=true
    depends_on:
      - postgres
      - fourstore
      - s3
    links:
      - postgres
      - fourstore
      - s3
    volumes:
      - .:/usr/local/src
      - data:/data

  anansi:
    image: acropolis
    command: /usr/sbin/crawld -c /usr/etc/crawl.conf -f
    depends_on:
      - postgres
      - fourstore
      - s3
    links:
      - postgres
      - fourstore
      - s3
    volumes_from:
      - acropolis

  twine-anansi:
    image: acropolis
    command: /usr/sbin/twine-writerd -d -c /usr/etc/twine-anansi.conf -f
    depends_on:
      - postgres
      - fourstore
      - s3
    links:
      - postgres
      - fourstore
      - s3
    volumes_from:
      - acropolis
      
  twine-spindle:
    image: acropolis
    command: /usr/sbin/twine-writerd -d -c /usr/etc/twine.conf -f
    depends_on:
      - postgres
      - fourstore
      - s3
    links:
      - postgres
      - fourstore
      - s3
    volumes_from:
      - acropolis
      
  twine-remote:
    image: acropolis
    command: /usr/bin/python3 /usr/local/src/docker/remote.py
    depends_on:
      - postgres
      - fourstore
      - s3
    links:
      - postgres
      - fourstore
      - s3
    ports:
      - 8000:8000
    volumes_from:
      - acropolis
    
  quilt:
    image: acropolis
    command: /usr/sbin/apache2 -D FOREGROUND
    depends_on:
      - postgres
      - fourstore
      - s3
    links:
      - postgres
      - fourstore
      - s3
    ports:
      - 80:80
    volumes_from:
      - acropolis
    
  postgres:
    image: postgres:9.1
    ports:
      - 5432:5432

  fourstore:
    image: vm-10-100-0-25.ch.bbcarchdev.net/4store

  s3:
    image: vm-10-100-0-25.ch.bbcarchdev.net/s3

volumes:
  data: {}
