version: '2'
services:
  acropolis-test:
    image: acropolis-test
    container_name: acropolis-test
    entrypoint:
      - docker/init_db.sh
    environment:
      - ACROPOLIS_HOSTNAME=acropolis.localhost
    command: supervisord
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - fourstore
      - s3
    links:
      - postgres
      - fourstore
      - s3
    expose:
     - "80"
     - "8000"
    ports:
     - 80:80

  pytest:
    container_name: pytest
    command: pytest
    build:
      context: .
      dockerfile: Dockerfile-pytest
    depends_on:
      - acropolis-test
    links:
      - acropolis-test:acropolis.localhost
      - acropolis-test:acropolis

    volumes:
      - ./test:/acropolis_test

  postgres:
    image: postgres:9.1
    expose:
      - "5432"

  # Tstore for the output of twine-anansi and the command line client twine
  fourstore:
    image: cgueret/4store

  # S3 used to cache objects from Anansi and data processing output from Spindle
  s3:
    image: lphoward/fake-s3
    expose:
      - 80
    command: -r /fakes3_root -p 80
